In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings('ignore')

# Segment 0

In [19]:
df_0 = pd.read_csv('segment_0.csv')

In [20]:
df_0.head()

,recommendationid,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,...,sentiment_scores_all_pos_vader,sentiment_score_all_pos_vader,sentiment_score_review_spacy,sentiment_score_noun_pos_spacy,sentiment_score_all_pos_spacy,consistency_noun_pos_vader,consistency_all_pos_vader,consistency_review_spacy,consistency_noun_pos_spacy,consistency_all_pos_spacy
0,157592673,english,"very fun game. the animals are very cute, the ...",1707068019,1707068019,True,0,0,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,0.218052,0.012121,0.237727,inconsistent,inconsistent,consistent,consistent,consistent
1,157554594,english,it's just super fun. i love pvpin friends,1707030713,1707030713,True,0,0,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,0.377778,0.316667,0.377778,inconsistent,inconsistent,consistent,consistent,consistent
2,157524237,english,funny,1706994639,1706994639,True,0,0,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,0.250000,0.000000,0.250000,inconsistent,inconsistent,consistent,inconsistent,consistent
3,157498882,english,NaN,1706973887,1706973887,True,0,0,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,0.000000,0.000000,0.000000,inconsistent,inconsistent,inconsistent,inconsistent,inconsistent
4,157457310,english,sharky go bonk,1706928253,1706928253,True,0,0,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,0.000000,0.000000,0.000000,inconsistent,inconsistent,inconsistent,inconsistent,inconsistent

In [21]:
# Assuming df is your DataFrame and 'attributes_patterns' is your column
df_0['attributes_patterns'] = df_0['attributes_patterns'].str.strip('[]').str.split(', ')

# Flatten the list of lists and count occurrences of each word
word_counts = Counter(word for words in df_0['attributes_patterns'] for word in words)

# Create a DataFrame from the word counts
df_word_counts = pd.DataFrame.from_dict(word_counts, orient='index', columns=['Count'])

# Reset the index
df_word_counts.reset_index(inplace=True)

# Rename the columns
df_word_counts.columns = ['Word', 'Count']

# Sort the DataFrame in descending order of the count
df_word_counts = df_word_counts.sort_values(by='Count', ascending=False)

# Reset the index after sorting
df_word_counts.reset_index(drop=True, inplace=True)

df_word_counts = df_word_counts[df_word_counts['Word'] != '']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ h1\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'’ t\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'/b ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ list\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ h3\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'* ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ b\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'* *\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ h2\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ url=https\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'] random\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'/list ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'//storage.googleapis.com/rebos_american_hamburger_stash/grabbing_issues_2.mp4 ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'//storage.googleapis.com/rebos_american_hamburger_stash/grabbing_issues.mp4 ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ /h3\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'/h2 ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'/h1 ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'//storage.googleapis.com/rebos_american_hamburger_stash/another_bomba_bridge.mp4 ]\'']

# Get the top 200 words
top_200_words = df_word_counts['Word'].head(200)
top_200_words.reset_index(drop=True, inplace=True)
top_200_words

0            'good game'
1             'fun game'
2             'much fun'
3           'great game'
4          'quick match'
             ...
195              'gg ez'
196     'various levels'
197            'bs luck'
198    'funny mechanics'
199         'crazy ride'
Name: Word, Length: 200, dtype: object

In [22]:
df_word_counts.head(20)

                  Word  Count
1          'good game'     24
2           'fun game'     22
3           'much fun'     17
4         'great game'     16
5        'quick match'      9
6          'super fun'      8
7         'funny game'      8
8   'negative reviews'      8
9       'awesome game'      7
10      'amazing game'      7
11        'nemo bucks'      6
12         'best game'      6
13         'long time'      6
14      'cute animals'      5
15        'best party'      5
16        'great time'      4
17       'issues such'      4
19       'bad reviews'      4
20            'good ☐'      4
21      'offline play'      4

In [23]:
# Iterate over the top 200 words and create new columns in the original DataFrame
for word in top_200_words:
    df_0[word] = df_0['attributes_patterns'].apply(lambda x: 1 if word in x else 0)

In [24]:
df_0

,recommendationid,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,...,'lame ones','additional costumes','significant amount','many controversies','right vibe','gg ez','various levels','bs luck','funny mechanics','crazy ride'
0,157592673,english,"very fun game. the animals are very cute, the ...",1707068019,1707068019,True,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
1,157554594,english,it's just super fun. i love pvpin friends,1707030713,1707030713,True,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
2,157524237,english,funny,1706994639,1706994639,True,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
3,157498882,english,NaN,1706973887,1706973887,True,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
4,157457310,english,sharky go bonk,1706928253,1706928253,True,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,146648087,english,most anticipating game i was looking forward t...,1695218719,1700608565,True,5,0,0.546022,0,...,0,0,0,0,0,0,0,0,0,0
510,146647082,english,great game no idea where all the negative revi...,1695217729,1695217729,True,1,0,0.522772,0,...,0,0,0,0,0,0,0,0,0,0
511,146646494,english,hilarious fun.,1695217110,1695217110,True,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
512,146644722,english,the updates are on point,1695215168,1700763492,True,0,0,0.000000,6,...,0,0,0,0,0,0,0,0,0,0
513,146644441,english,super fun! the best party game so far.,1695214841,1695214841,True,0,0,0.000000,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
Y = df_0['voted_up']

#Top 15 feature
X = df_0[["'much inconsistency'",
        "'gg ez'",
        "'grey screen'",
        "'current state'",
        "'additional levels'",
        "'new game'",
        "'game unplayable'",
        "'launch day'",
        "'other games'",
        "'offline play'",
        "'i bet'",
        "'weekly missions'",
        "'cute game'",
        "'real money'",
        "'more time'"]]

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

# Initialize and train the Logistic Regression model
logistic_model = LogisticRegression()
logistic_model.fit(X_train, Y_train)


Y_pred = logistic_model.predict(X_test)

# Calculate accuracy, confusion matrix, and classification report
accuracy = accuracy_score(Y_test, Y_pred)
conf_matrix = confusion_matrix(Y_test, Y_pred)

accuracy, conf_matrix,

(0.9483870967741935,
 array([[  0,   8],
        [  0, 147]]))

In [27]:
# Extracting the coefficients of the logistic regression model
coefficients = logistic_model.coef_[0]

feature_names = X.columns
coefficients_df = pd.DataFrame({'Feature': feature_names, 'Coefficient': coefficients})

coefficients_df

                 Feature  Coefficient
0   'much inconsistency'    -0.835680
1                'gg ez'    -0.835680
2          'grey screen'    -0.835680
3        'current state'    -1.469749
4    'additional levels'    -0.710064
5             'new game'    -0.710064
6      'game unplayable'    -1.371430
7           'launch day'    -0.710064
8          'other games'    -1.140730
9         'offline play'    -0.603670
10               'i bet'    -0.621314
11     'weekly missions'    -0.661596
12           'cute game'    -0.557364
13          'real money'     0.071892
14           'more time'     0.071892

# Segment 1

In [28]:
df_1 = pd.read_csv('segment_1.csv')

In [29]:
df_1.head()

,recommendationid,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,...,sentiment_scores_all_pos_vader,sentiment_score_all_pos_vader,sentiment_score_review_spacy,sentiment_score_noun_pos_spacy,sentiment_score_all_pos_spacy,consistency_noun_pos_vader,consistency_all_pos_vader,consistency_review_spacy,consistency_noun_pos_spacy,consistency_all_pos_spacy
0,157603005,english,fun game to play when you've had a long day an...,1707077354,1707077354,True,0,0,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,0.031481,0.143333,0.031481,consistent,inconsistent,consistent,consistent,consistent
1,157602265,english,pros:\nanimals\nparty\nfunny mechanics\na bunc...,1707076676,1707076676,True,0,0,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,-0.000231,0.166667,-0.011719,consistent,inconsistent,inconsistent,consistent,inconsistent
2,157598111,english,10/10 would drop kick a cat without feeling bad,1707072837,1707072837,True,0,1,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,-0.700000,0.000000,-0.700000,inconsistent,inconsistent,inconsistent,inconsistent,inconsistent
3,157588222,english,game has been out for 4 months and they only a...,1707064205,1707064205,False,0,0,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,-0.116856,0.089899,-0.091288,inconsistent,inconsistent,consistent,inconsistent,consistent
4,157571234,english,"i wanted a silly game, i got that.\ni wanted s...",1707049256,1707049256,True,0,1,0.0,0,...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0,0.150000,-0.166667,0.150000,consistent,inconsistent,consistent,inconsistent,consistent

In [30]:
# Assuming df is your DataFrame and 'attributes_patterns' is your column
df_1['attributes_patterns'] = df_1['attributes_patterns'].str.strip('[]').str.split(', ')

# Flatten the list of lists and count occurrences of each word
word_counts = Counter(word for words in df_1['attributes_patterns'] for word in words)

# Create a DataFrame from the word counts
df_word_counts = pd.DataFrame.from_dict(word_counts, orient='index', columns=['Count'])

# Reset the index
df_word_counts.reset_index(inplace=True)

# Rename the columns
df_word_counts.columns = ['Word', 'Count']

# Sort the DataFrame in descending order of the count
df_word_counts = df_word_counts.sort_values(by='Count', ascending=False)

# Reset the index after sorting
df_word_counts.reset_index(drop=True, inplace=True)

df_word_counts = df_word_counts[df_word_counts['Word'] != '']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ h1\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'’ t\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'/b ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ list\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ h3\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'* ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ b\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'* *\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ h2\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ url=https\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'] random\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'/list ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'//storage.googleapis.com/rebos_american_hamburger_stash/grabbing_issues_2.mp4 ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'//storage.googleapis.com/rebos_american_hamburger_stash/grabbing_issues.mp4 ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ /list\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'[ /h3\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'/h2 ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'/h1 ]\'']
df_word_counts = df_word_counts[df_word_counts['Word'] != '\'//storage.googleapis.com/rebos_american_hamburger_stash/another_bomba_bridge.mp4 ]\'']

# Get the top 200 words
top_200_words = df_word_counts['Word'].head(200)
top_200_words.reset_index(drop=True, inplace=True)
top_200_words

0             'good game'
1              'fun game'
2            'great game'
3                'game i'
4          'offline mode'
              ...
195       'other reviews'
196    'playable offline'
197          'casual fun'
198            'most fun'
199            'best way'
Name: Word, Length: 200, dtype: object

In [31]:
df_word_counts.head(20)

                    Word  Count
1            'good game'    341
2             'fun game'    314
3           'great game'    311
4               'game i'    201
5         'offline mode'    197
6     'negative reviews'    188
7             'much fun'    181
8            'super fun'    151
9            'best game'    111
10         'gang beasts'    103
11  'micro transactions'     90
12           'long time'     84
13        'offline play'     82
14          'local coop'     77
15        'amazing game'     76
16          'funny game'     75
17          'best party'     62
18           'great fun'     58
19          'real money'     58
20         'quick match'     57

In [13]:
# Iterate over the top 200 words and create new columns in the original DataFrame
for word in top_200_words:
    df_1[word] = df_1['attributes_patterns'].apply(lambda x: 1 if word in x else 0)

In [14]:
Y_1 = df_1['voted_up']

#Top 15 feature
X_1 = df_1[["'local coop'",
        "'offline mode'",
        "'couch coop'",
        "'local play'",
        "'internet connection'",
        "'fun game'",
        "'negative review'",
        "'good game'",
        "'micro transactions'",
        "'paid game'",
        "'great game'",
        "'much money'",
        "'quick match'",
        "'same game'",
        "'offline play'"]]

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X_train, X_test, Y_train, Y_test = train_test_split(X_1, Y_1, test_size=0.3, random_state=42)

# Initialize and train the Logistic Regression model
logistic_model = LogisticRegression()
logistic_model.fit(X_train, Y_train)


Y_pred = logistic_model.predict(X_test)

# Calculate accuracy, confusion matrix, and classification report
accuracy = accuracy_score(Y_test, Y_pred)
conf_matrix = confusion_matrix(Y_test, Y_pred)

accuracy, conf_matrix,

(0.8852785145888594,
 array([[   2,  341],
        [   5, 2668]]))

In [16]:
# Extracting the coefficients of the logistic regression model
coefficients = logistic_model.coef_[0]

feature_names = X_1.columns
coefficients_df = pd.DataFrame({'Feature': feature_names, 'Coefficient': coefficients})

coefficients_df

                  Feature  Coefficient
0            'local coop'    -2.107414
1          'offline mode'    -0.843607
2            'couch coop'    -1.380967
3            'local play'    -1.783502
4   'internet connection'    -1.174339
5              'fun game'     0.426367
6       'negative review'    -1.441528
7             'good game'     0.760982
8    'micro transactions'    -0.762281
9             'paid game'    -1.478076
10           'great game'     0.899843
11           'much money'    -2.051051
12          'quick match'    -0.944360
13            'same game'    -2.041211
14         'offline play'    -0.360901